name: Deployment Exercise 2
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
   lint:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4.2.4  
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/Package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
   Test:
      env:
        DB_USERNAME: "sanjaimavi"
        DB_PASSWORD: "sanj@1234"
      needs: lint
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm ci   
        - name: Test code
          id: run-tests
          run: npm test
        # - name: Upload a build Artifact
        #   if: failure() && steps.run-tests.outcome == 'failure'
        #   uses: actions/upload-artifact@v4.6.2
        #   with:
        #     name: build artifact
        #     path: |
        #         dist
        #         package.json
        - name: Db creds
          run: echo "db creds is $DB_USERNAME, and ${{ env.DB_PASSWORD }}"
   build:
       needs: Test
       runs-on: ubuntu-latest
       steps:
         - name: Get code
           uses: actions/checkout@v4
         - name: Cache Dependencies
           uses: actions/cache@v4.2.4
           with:
             path: ~/.npm
             key: deps-node-modules-${{ hashFiles('**/Package-lock.json')}}
         - name: Install dependencies
           run: npm ci   
         - name: run-build
           id: run-build
           run: npm run build
         - name: Upload a build Artifact
           if: failure() && steps.run-build.outcome == 'failure'
           uses: actions/upload-artifact@v4.6.2
           with:
              name: build artifact
              path: |
                dist
                package.json
   deploy:
       needs: build 
       runs-on: ubuntu-latest
       steps:
           - name: Get code
             uses: actions/checkout@v4
           - name: Cache Dependencies
             uses: actions/cache@v4.2.4
             with:
               path: ~/.npm
               key: deps-node-modules-${{ hashFiles('**/Package-lock.json')}}
           - name: Install dependencies
             run: npm ci
           - name: Build code
             run: npm run build
           - name: get artifacts
             uses: actions/download-artifact@v5
             with:
               name: build artifact
           - name: Output contents
             run: ls
           - name: Deploy code
             run: echo "DB user name is ${{ secrets.DB_USERNAME }}"
        
   report:
       needs: [lint, deploy]
       if: failure()
       runs-on: ubuntu-latest
       steps:
        - name: output information
          run: |
           echo "Something went wrong"
           echo "${{ GitHub }}"          
 
